name: gigd-devops-github-action
on:
  push:
    branches:
      - "main"
jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # installer les dépendances
      - name: Install and build
        run: npm install && npm run build
      # les test unitaire
      - name: run unit test
        run: npm run test
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIHUB_PAGES_KEY }}
          publish_dir: ./build
